### ISSUE TITLE
introduce volumes

### ISSUE THREAD

**Issue by cordoval** [alex/ecs-terraform#1]
thank you, exactly what i needed, btw can we introduce this for volumes since the example from amazon has it?

``` json
resource "aws_ecs_task_definition" "test-http" {
    family = "test-http"
   volume = ....
    container_definitions = "${file("task-definitions/test-http.json")}"
}
```

**Comment by alex** [comment]
Everything in `services.tf` is intended to be provided by your application. Probably it should be moved into an `examples/` directory or something. All you need to do is write your own `aws_ecs_task_definition` resource and provide `container_definitions`.

**Comment by cordoval** [comment]
yes agree
