### ISSUE TITLE
would be very useful to introduce how to handle the registry even if it is public

### ISSUE THREAD

**Issue by cordoval** [alex/ecs-terraform#2]

**Comment by alex** [comment]
Dealing with the registry is outside the scope of this infrastructure (it's my visiion that mostly people will just use ECR once it launches). What were you looking for?

**Comment by cordoval** [comment]
you mean DCR docker container registry from aws right?

question: target = "HTTP:8080/hello-world" if my container port is just 80 that should change to 80?

**Comment by alex** [comment]
For the healthcheck? Yes, the healthcheck target port on your load balancer
should match the port you expose on the host, from your container.

On Mon, Dec 7, 2015 at 4:11 PM, Luis Cordova notifications@github.com
wrote:

> you mean DCR docker container registry from aws right?
> 
> question: target = "HTTP:8080/hello-world" if my container port is just 80
> that should change to 80?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/ecs-terraform/issues/2#issuecomment-162664590.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by cordoval** [comment]
did you see this https://github.com/alex/ecs-terraform/pull/3/files#r46878810 ?

**Comment by cordoval** [comment]
i think everything is setup, perhaps i misinterpreted the documentation in which the tasks would have launched themselves automatically upon provisioning? is this not the case? if not the case then i guess that is what you do with the python code... hmm really thought this was done automatically for some reason. I mean my web is a persistent service so it always have to run no?

**Comment by alex** [comment]
Services should start running when the cluster comes up.

On Mon, Dec 7, 2015 at 4:33 PM, Luis Cordova notifications@github.com
wrote:

> i think everything is setup, perhaps i misinterpreted the documentation in
> which the tasks would have launched themselves automatically upon
> provisioning? is this not the case? if not the case then i guess that is
> what you do with the python code... hmm really thought this was done
> automatically for some reason
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/ecs-terraform/issues/2#issuecomment-162670400.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by cordoval** [comment]
weird, the cluster is up, but nothing ran... the service does not show up though, weird

**Comment by cordoval** [comment]
I am not trying to pick on you, but i notice it creates two clusters, one main and one default, so definitely the autoscaling group or the launch configuration needs one more param to tell it to point to the right cluster. I see this is done with var.ecs_cluster_name but not sure why it is still creating a default cluster and registering the instances there ...

you rock man again, not trying to be mean or uneducated.

<img width="1277" alt="screen shot 2015-12-07 at 4 49 41 pm" src="https://cloud.githubusercontent.com/assets/328359/11640820/a18146a6-9d02-11e5-9b2b-61beab4a38cb.png">

**Comment by cordoval** [comment]
aws_ecs_cluster.main.id -> is default!

**Comment by cordoval** [comment]
can i send a PR fixing that?

**Comment by alex** [comment]
Sure

On Mon, Dec 7, 2015 at 4:53 PM, Luis Cordova notifications@github.com
wrote:

> aws_ecs_cluster.main.id -> is default!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/ecs-terraform/issues/2#issuecomment-162676695.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by cordoval** [comment]
i think it is rather this

`user_data = "#!/bin/bash\necho ECS_CLUSTER='${var.ecs_cluster_name}' > /etc/ecs/ecs.config"`

**UPDATE**
maybe the > -> >>

for some reason is not registering to the right place

**Comment by cordoval** [comment]
hmm couldn't find the problem, no matter even if i hard code that  to main it will just not take it or listen to it. I will just use default as my main name and let it do it.

**Comment by cordoval** [comment]
do you think this merits a ticket on terraform repo?

**Comment by alex** [comment]
If you can make a specific actionable bug report with a self-contained
reproducing example, absolutely!

On Mon, Dec 7, 2015 at 5:46 PM, Luis Cordova notifications@github.com
wrote:

> do you think this merits a ticket on terraform repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/ecs-terraform/issues/2#issuecomment-162693669.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by cordoval** [comment]
your repo is the very specific actionable :)
