### ISSUE TITLE
https://hub.docker.com/r/alexgaynor/test-http/ availability in dockerfile?

### ISSUE THREAD

**Issue by cordoval** [alex/ecs-terraform#4]
do you have the dockerfile and sourcecode of this docker image somewhere?

thanks

i think it comes handy for testing certain things

**Comment by alex** [comment]
the source is https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example and the dockerfile is a minimal one that copies `example.yml` and a jar into the repo and runs a JVM8.

It should not be relied upon for anything.

**Comment by cordoval** [comment]
i ask because my image of amazon/simple-php-app for ecs died immediately after being hit and also i have to change ports back to yours since there were some issues with different ports.

**Comment by cordoval** [comment]
can you please pass me the dockerfile? i am running in all sorts of issues
